### ISSUE TITLE
Add JARVIS on Messenger

### ISSUE THREAD

**Issue by swapagarwal** [rafej/botalist#2]
Greetings. This template is for people submitting their bot to the index, if you are making an issue related to something else you can safely remove this text!

**What you need (fill in the blanks)**
- The bot's name: JARVIS on Messenger
- A link to the bot link (usually through http://m.me, eg. https://m.me/cnn for CNN, https://m.me/wsj for WSJ): https://m.me/J.A.R.V.I.S.on.Messenger
- The name of the company or individual who published the bot: Swapnil Agarwal
- A link to the page relevant to the entity who published the bot: https://www.facebook.com/swap.agarwal
- The description of the bot: Just A Rather Very Intelligent System, now on Messenger! JARVIS is a community-driven bot that aims to be as simple as possible to serve humans with their everyday tasks.
- Some categories which apply to the bot (can be either `game`, `productivity`, `on demand`, `fun`, `media`, or `money`): `productivity`, `on demand`, `fun`
- Some relevant tags/keywords which apply to the bot (can be whatever you want to make your bot more searchable): jarvis, chatbot, assistant

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by swapagarwal** [comment]
You can request access here: https://www.facebook.com/J.A.R.V.I.S.on.Messenger/posts/551338921704902

**Comment by paked** [comment]
Thanks for the PR @swapagarwal!

![https://media.giphy.com/media/brDwVn5kGIz3W/giphy.gif](https://media.giphy.com/media/brDwVn5kGIz3W/giphy.gif)

**Comment by swapagarwal** [comment]
Woah, that was quick! :+1:
