### ISSUE TITLE
Marina by Alterra.ai, a virtual AI travel agent

### ISSUE THREAD

**Issue by bilb02** [rafej/botalist#3]
- The bot's name: Marina Alterra
- A link to the bot link: not approved yet, app ID = 1348805941802031
- The name of the company or individual who published the bot: Alterra.ai
- A link to the page relevant to the entity who published the bot: https://www.facebook.com/alterra.cc/info/?tab=page_info
- The description of the bot: Marina Alterra is a virtual AI travel agent, a messenger bot (powered by algorithms, not humans). It helps travelers to discover where to go on vacation and book hotels there.
- Some categories which apply to the bot: travel
- Some relevant tags/keywords which apply to the bot: vacation, hotel, AI
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers: cannot find the link; app ID = 1348805941802031
- Telegram version: https://telegram.me/AlterraBot

**Comment by rafej** [comment]
Thanks for the PR! 😄 👍
