### ISSUE TITLE
Botsify - Help people making chatbots

### ISSUE THREAD

**Issue by usamanoman** [rafej/botalist#5]
Greetings. This template is for people submitting their bot to the index, if you are making an issue related to something else you can safely remove this text!

**What you need (fill in the blanks)**
- The bot's name:
  Botsify
- A link to the bot link (usually through http://m.me, eg. https://m.me/cnn for CNN, https://m.me/wsj for WSJ):
  https://www.botsify.com
- The name of the company or individual who published the bot:
  Usama Noman
- A link to the page relevant to the entity who published the bot:
  https://web.facebook.com/botsifyapp/
- The description of the bot:
  Botsify helps you create facebook messenger chatbot for your business/page without any coding.

You can artificial intelligent chatbots with our technology with no technical knowledge require. Technical mates can go extra mile with Botsify by integrating their API with Chatbot to make it extra effective. People can do analysis on different behavior of their bots and also run marketing campaigns to the people who opted for it.

With over a billion user you can now double you conversions with messenger chatbot.
- Some categories which apply to the bot (can be either `game`, `productivity`, `on demand`, `fun`, `media`, or `money`):
  business
- Some relevant tags/keywords which apply to the bot (can be whatever you want to make your bot more searchable):
  messenger bot builder, messeger chatbots for free, facebook messenger bots
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers (eg. https://www.facebook.com/permalink.php?story_fbid=473383312871039&id=471938779682159):

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by paked** [comment]
@usamanoman I'd love to work on getting this merged in, however it seems that your website is offline. Once you've gotten that resolved, let me know!

**Comment by mshirlaw** [comment]
Added in https://github.com/rafej/botalog/pull/10
