### ISSUE TITLE
Wally

### ISSUE THREAD

**Issue by emcro** [rafej/botalist#6]
Greetings. This template is for people submitting their bot to the index, if you are making an issue related to something else you can safely remove this text!

**What you need (fill in the blanks)**
- The bot's name: Wally
- A link to the bot link (usually through http://m.me, eg. https://m.me/cnn for CNN, https://m.me/wsj for WSJ): http://m.me/wallythebot
- The name of the company or individual who published the bot: Mobile Media LLC
- A link to the page relevant to the entity who published the bot: https://wallythebot.com/
- The description of the bot: Wally helps you get the most points from the credit cards you already have, and get the ones you need, to travel like a boss.
- Some categories which apply to the bot (can be either `game`, `productivity`, `on demand`, `fun`, `media`, or `money`): money
- Some relevant tags/keywords which apply to the bot (can be whatever you want to make your bot more searchable): money, credit card, travel, award, flight, flying, airlines, hotels
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers (eg. https://www.facebook.com/permalink.php?story_fbid=473383312871039&id=471938779682159): Approved yesterday :)

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by rafej** [comment]
Thanks for the PR! 😄 
![](https://media.giphy.com/media/Cj3Ce7e8h2EKY/giphy.gif)
