### ISSUE TITLE
New bot: DropBot

### ISSUE THREAD

**Issue by emcro** [rafej/botalist#7]
Greetings. This template is for people submitting their bot to the index, if you are making an issue related to something else you can safely remove this text!

**What you need (fill in the blanks)**
- The bot's name: DropBot
- A link to the bot link (usually through http://m.me, eg. https://m.me/cnn for CNN, https://m.me/wsj for WSJ): http://m.me/550785301770397
- The name of the company or individual who published the bot: Emmanuel Crouvisier
- A link to the page relevant to the entity who published the bot: https://mydropbot.com/
- The description of the bot: DropBot gets you the best prices on the things you want by letting you know when to buy.
- Some categories which apply to the bot (can be either `game`, `productivity`, `on demand`, `fun`, `media`, or `money`): Shopping
- Some relevant tags/keywords which apply to the bot (can be whatever you want to make your bot more searchable): Shopping, Amazon, Price, Deal
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers (eg. https://www.facebook.com/permalink.php?story_fbid=473383312871039&id=471938779682159): Already live!

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by mshirlaw** [comment]
Added in https://github.com/rafej/botalog/pull/10
