### ISSUE TITLE
20Bot

### ISSUE THREAD

**Issue by j0k3r** [rafej/botalist#8]
Greetings. This template is for people submitting their bot to the index, if you are making an issue related to something else you can safely remove this text!

**What you need (fill in the blanks)**
- The bot's name: 20Bot
- A link to the bot link (usually through http://m.me, eg. https://m.me/cnn for CNN, https://m.me/wsj for WSJ): https://m.me/20minutes
- The name of the company or individual who published the bot: 20 Minutes
- A link to the page relevant to the entity who published the bot: http://www.20minutes.fr/
- The description of the bot: Brings to you top stories, breaking news, etc. on demande. Also send top stories every day at 1pm. It can also reply to some custom request.
- Some categories which apply to the bot (can be either `game`, `productivity`, `on demand`, `fun`, `media`, or `money`): media
- Some relevant tags/keywords which apply to the bot (can be whatever you want to make your bot more searchable): media, actu
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers (eg. https://www.facebook.com/permalink.php?story_fbid=473383312871039&id=471938779682159): Already published :white_check_mark: 

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by mshirlaw** [comment]
Added in https://github.com/rafej/botalog/pull/10
