### ISSUE TITLE
Start A Fire Bot

### ISSUE THREAD

**Issue by StartAFireCom** [rafej/botalist#9]
- The bot's name: Start A Fire
- A link to the bot link: https://www.messenger.com/t/startafirecom/
- The name of the company or individual who published the bot: Start A Fire
- A link to the page relevant to the entity who published the bot: https://www.facebook.com/StartAFireCom/
  www.startafire.com
- The description of the bot:
  Start A Fire help users get value from the links they share. Offering badges that go alongside user content and unique recommendation systems that ensure the content that goes viral is brand-worthy.
  The tool enables those who share content to get the full value of that shared content.
- Some categories which apply to the bot: Marketing
- Some relevant tags/keywords which apply to the bot: #marketing #content #contentmarketing #socialmedia #share
- If the bot has not been officially accepted by Facebook, a link where people can comment to become testers (eg. https://www.facebook.com/permalink.php?story_fbid=473383312871039&id=471938779682159):

If you've completed these steps you're ready to go, also:
![this gag is much better in preview mode... trust me](https://media.giphy.com/media/3o7ZeTmU77UlPyeR2w/giphy.gif)

**Comment by mshirlaw** [comment]
Added in https://github.com/rafej/botalog/pull/10
